export const STOREFRONT_NAME = process.env.NEXT_PUBLIC_STOREFRONT_NAME || "";
export const CHECKOUT_TOKEN = "checkoutToken";
export const API_URI = process.env.NEXT_PUBLIC_API_URI || "";
export const DEMO_MODE = process.env.NEXT_PUBLIC_DEMO_MODE === "true";
export const HOMEPAGE_MENU = process.env.NEXT_PUBLIC_HOMEPAGE_MENU || "";
export const GEOLOCATION = process.env.NEXT_PUBLIC_GEOLOCATION === "true";
export const CHANNEL_SLUG = process.env.NEXT_PUBLIC_DEFAULT_CHANNEL || "";
export const AWS_MEDIA_BUCKET = process.env.NEXT_PUBLIC_AWS_MEDIA_BUCKET || "";
export const GA_TRACKING_ID = process.env.NEXT_PUBLIC_GA_TRACKING_ID!;
export const VERCEL_URL = process.env.NEXT_PUBLIC_VERCEL_URL;
